/* Generated By:JJTree&JavaCC: Do not edit this line. JuuConstants.java */
package net.gcalc.juu.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JuuConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEBUG = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int PROC = 9;
  /** RegularExpression Id. */
  int WHILE = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 12;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 13;
  /** RegularExpression Id. */
  int HEX_LITERAL = 14;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 15;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 16;
  /** RegularExpression Id. */
  int EXPONENT = 17;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 18;
  /** RegularExpression Id. */
  int IDENTIFIER = 19;
  /** RegularExpression Id. */
  int LETTER = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 22;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 23;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"debug\"",
    "\"if\"",
    "\"proc\"",
    "\"while\"",
    "\"else\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<BOOLEAN_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\":=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"%\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"[\"",
    "\"]\"",
  };

}
