/* Generated By:JavaCC: Do not edit this line. JuuTreeConstants.java Version 5.0 */
package net.gcalc.juu.parser;

public interface JuuTreeConstants
{
  public int JJTBLOCK = 0;
  public int JJTVOID = 1;
  public int JJTDEBUG = 2;
  public int JJTLETREC = 3;
  public int JJTLET = 4;
  public int JJTLHS = 5;
  public int JJTRHS = 6;
  public int JJTIFSTATEMENT = 7;
  public int JJTWHILESTATEMENT = 8;
  public int JJTPROC = 9;
  public int JJTPARAMETERLIST = 10;
  public int JJTDISJUNCTION = 11;
  public int JJTCONJUNCTION = 12;
  public int JJTEQUAL = 13;
  public int JJTEQ = 14;
  public int JJTNEQ = 15;
  public int JJTORDERREL = 16;
  public int JJTLE = 17;
  public int JJTLT = 18;
  public int JJTGE = 19;
  public int JJTGT = 20;
  public int JJTSUM = 21;
  public int JJTPLUS = 22;
  public int JJTMINUS = 23;
  public int JJTMOD = 24;
  public int JJTPROD = 25;
  public int JJTMULT = 26;
  public int JJTDIV = 27;
  public int JJTIMPLICITMULT = 28;
  public int JJTPOS = 29;
  public int JJTNEG = 30;
  public int JJTEXP = 31;
  public int JJTVECTOR = 32;
  public int JJTFUNCTIONCALL = 33;
  public int JJTARGUMENTLIST = 34;
  public int JJTIDENTIFIER = 35;
  public int JJTINTEGER = 36;
  public int JJTFLOATINGPOINT = 37;
  public int JJTBOOLEAN = 38;


  public String[] jjtNodeName = {
    "Block",
    "void",
    "debug",
    "LETREC",
    "LET",
    "LHS",
    "RHS",
    "IfStatement",
    "WhileStatement",
    "Proc",
    "ParameterList",
    "Disjunction",
    "Conjunction",
    "Equal",
    "EQ",
    "NEQ",
    "OrderRel",
    "LE",
    "LT",
    "GE",
    "GT",
    "Sum",
    "PLUS",
    "MINUS",
    "Mod",
    "Prod",
    "MULT",
    "DIV",
    "IMPLICITMULT",
    "POS",
    "NEG",
    "EXP",
    "Vector",
    "FunctionCall",
    "ArgumentList",
    "Identifier",
    "Integer",
    "FloatingPoint",
    "Boolean",
  };
}
/* JavaCC - OriginalChecksum=495d1f7d7936ac352e5d4a3c5e8900f7 (do not edit this line) */
